sudo: required
dist: xenial
language: java
jdk:
    - openjdk8
    - openjdk11
env:
    - RUNTIME=ol RUNTIME_VERSION=20.0.0.6
    - RUNTIME=ol RUNTIME_VERSION=20.0.0.3
    - RUNTIME=wlp RUNTIME_VERSION=20.0.0.6
    - RUNTIME=wlp RUNTIME_VERSION=20.0.0.3
cache:
    directories:
        - $HOME/.m2
before_install:
    - echo "Deleting old .m2 artifacts..."
    - rm -rf $HOME/.m2/repository/net/wasdev
    - rm -rf $HOME/.m2/repository/io/openliberty
    - echo 'Installing ci.ant lib...'
    - git clone https://github.com/OpenLiberty/ci.ant.git ./ci.ant
    - cd ./ci.ant
    - mvn clean install
    - cd ..
    - echo 'Installing ci.common lib...'
    - git clone https://github.com/OpenLiberty/ci.common.git ./ci.common
    - cd ./ci.common
    - mvn clean install
    - cd ..
script:
    - travis_wait 40 mvn verify -Ponline-its -Dinvoker.streamLogs=true -Druntime=$RUNTIME -DruntimeVersion=$RUNTIME_VERSION
