environment:
    matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 19.0.0.6
          RUNTIME: ol
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 19.0.0.9
          RUNTIME: ol
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 19.0.0.6
          RUNTIME: wlp
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"
          RUNTIME_VERSION: 19.0.0.9
          RUNTIME: wlp

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\ci-maven
    - ps: .\appveyor.ps1

before_build:
    - cmd: |
        echo "Installing ci.ant lib..."
        git clone https://github.com/cherylking/ci.ant.git ci.ant
        cd ci.ant
        git checkout fixPackageArchiveProblem
        mvn clean install
        cd..
        echo "Installing ci.common lib..."
        git clone https://github.com/OpenLiberty/ci.common.git ci.common
        cd ci.common
        mvn clean install
        cd..

build_script:
    - "echo %WLP_VERSION%"
    - "mvn verify -Ponline-its -Dinvoker.streamLogs=true -Druntime=%RUNTIME% -DruntimeVersion=%RUNTIME_VERSION%"

test: off
